receivers:
  docker_stats:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:
  opencensus:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          static_configs:
            - targets: ["localhost:8888"]
  zipkin:

processors:
  batch:

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      record:
        traceID: traceid
      attributes:
        container.name: "container_name"
        k8s.cluster.name: "k8s_cluster_name"
        severity: "severity"
      resource:
        resource.name: "resource_name"
        severity: "severity"

  prometheusremotewrite:
    endpoint: http://mimir:9009/api/v1/push

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [jaeger,opencensus,otlp,zipkin]
      processors: [batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [hostmetrics,docker_stats,opencensus,otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
